/*
* @Author:    Pratyush Kar (2013A7PS029P),
*             Ayush Kataria (2013A7PS028P)
* @Email:     f2013029@pilani.bits-pilani.ac.in,
*             f2013028@pilani.bits-pilani.ac.in
* @Gp Number: 52
* @File Name: driver.c
* @Date:      2016-03-05 12:30:36
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "parserUtils.h"
#include "parser.h"

int main(int argc, char const *argv[])
{
    char grammar_filename[] = "./Grammar/final_grammar.txt";
    printf("######################## Deliverables ########################\n");
    printf("FIRST and FOLLOW set automation. ----> Done\n");
    printf("Both lexical and syntax analysis modules implemention. ---> Done\n");
    printf("##############################################################\n");
    printf("\nPress option for the defined task:\n");
    printf("1. For removal of comments - print the comment free code on the console.\n");
    printf("2. For printing the token list (on the console) generated by the lexer.\n");
    printf("3. For parsing to verify the syntactic correctness of the input source code.\n");
    printf("4. For creating the parse tree and printing it appropriately\n");
    printf("Option: ");
    int option;
    scanf("%d", &option);
    if(option == 1)
    {
        if(argc < 2)
        {
            fprintf(stderr, "USAGE: %s <testcase filename>\n", argv[0]);
            return -1;
        }
        const char* src_code_filename = argv[1];
        printFileWithoutComments(src_code_filename);
    }
    else if(option == 2)
    {
        if(argc < 2)
        {
            fprintf(stderr, "USAGE: %s <testcase filename>\n", argv[0]);
            return -1;
        }
        const char* src_code_filename = argv[1];
        printTokenList(src_code_filename);
    }
    else if(option == 3 || option == 4)
    {
        if(option == 3 && argc < 2)
        {
            fprintf(stderr, "USAGE: %s <testcase filename>\n", argv[0]);
            return -1;
        }
        if(option == 4 && argc < 3)
        {
            fprintf(stderr, "USAGE: %s <testcase filename> <parse tree output filename>\n", argv[0]);
            return -1;
        }
        const char* src_code_filename = argv[1];
        grammar rulelist = getRuleList(grammar_filename);
        table T = initialiseParserTable();
        createParseTable(rulelist, T);
        parseTree PT = parseInputSourceCode(src_code_filename, rulelist, T);
        if(option == 4)
        {
            const char* parse_tree_filename = argv[2];
            printParseTree(PT, parse_tree_filename);
        }
    }
    else
        printf("Wrong option entered.\n");
    return 0;
}