/*
* @Author: Pratyush Kar
* @Date:   2016-03-04 01:07:01
* @Last Modified by:   Pratyush Kar
* @Last Modified time: 2016-03-04 01:47:23
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "parserUtils.h"
#include "parser.h"

int main(int argc, char const *argv[])
{
    char grammar_filename[] = "./Grammar/final_grammar.txt";
    printf("Deliverables:\n");
    printf("FIRST and FOLLOW set automation. ----> Done\n");
    printf("Both lexical and syntax analysis modules implemention. ---> Done\n");
    printf("\nPress option for the defined task:\n");
    printf("1. For removal of comments - print the comment free code on the console.\n");
    printf("2. For printing the token list (on the console) generated by the lexer.\n");
    printf("3. For parsing to verify the syntactic correctness of the input source code.\n");
    printf("4. For creating the parse tree and printing it appropriately\n");
    printf("Option: ");
    int option;
    scanf("%d", &option);
    if(option == 1)
    {
        if(argc < 2)
        {
            fprintf(stderr, "%s <testcase filename>\n", argv[0]);
            return -1;
        }
        const char* src_code_filename = argv[1];
        // do something
        printf("do something\n");
    }
    else if(option == 2)
    {
        if(argc < 2)
        {
            fprintf(stderr, "%s <testcase filename>\n", argv[0]);
            return -1;
        }
        const char* src_code_filename = argv[1];
        // testcase zero line numbers are incorrect
        printTokenList(src_code_filename);
    }
    else if(option == 3 || option == 4)
    {
        if(option == 3 && argc < 2)
        {
            fprintf(stderr, "%s <testcase filename>\n", argv[0]);
            return -1;
        }
        if(option == 4 && argc < 3)
        {
            fprintf(stderr, "%s <testcase filename> <parse tree output filename>\n", argv[0]);
            return -1;
        }
        const char* src_code_filename = argv[1];
        grammar rulelist = getRuleList(grammar_filename);
        table T = createParseTable(rulelist);
        parseTree PT = parseInputSourceCode(src_code_filename, rulelist, T);
        if(option == 4)
        {
            const char* parse_tree_filename = argv[2];
            printParseTree(PT, parse_tree_filename);
        }
    }
    else
        printf("Wrong option entered.\n");
    return 0;
}